### PR TITLE
add ultra sound relay

### PR DESCRIPTION
**Pull request by JustinDrake**
consider adding relay.ultrasound.money :)

### CODE REVIEW

**Comment by shibug** [comment]
Would you mind sharing some documentation about this relay and why it is better than the one I already have?  Looking for public documentation

**Comment by shibug** [comment]
Got it: https://relay.ultrasound.money/

**Comment by JustinDrake** [comment]
One of the main features is credible neutrality. The relay does not censor blocks.

**Comment by shibug** [comment]
I like that.  Will merge next week.  Working on something else.  Thanks for the patch

**Comment by JustinDrake** [comment]
@shibug: Still interested in merging? :)

**Comment by shibug** [comment]
Sorry, almost forgot. Will review it todayRegards,Shibu GopeOn Jan 22, 2023, at 5:30 AM, Justin ***@***.***> wrote:﻿
@shibug: Still interested in merging? :)

**Review by shibug — APPROVED** [review]

**Pull request merged**
